language: node_js
node_js:
- '5'
install:
- npm install
script:
- NODE_ENV=production webpack -p
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: a+ux2lHI64EmTqZb5uGZqBNPC0dwEs/mv1uP6FQImcNJeOdLCSAvB9n8D7mV0phr+OoalG8DVxPXfshcs0YqGY+ZdSi7U1ki77CdZzSMopwnHEDgSlGkjJB98JkLPPbLYxommy6Y6Gp7SgzSqJx4TPEQLUv/I0Fd7v94qS/2ryQWFs/ykaGW1Tye8RA/9l/ftzDRFpyYzG1DG05f3i5KcRYKNnxWC3sa5VZ+s4OvJr9kkqxL1HFuE10kUMB+Al5kbW83/9gx26lh9cJDsKK+S1I8nA74324E5TrqpIAhCPu1wtqyxznFb7l2PTsexRIPPyRAs1/8zm4cC+fPGeZwX3Vlu8SES/GFUCATLoy6KSUFhwpgnmLZm7x8GZV61VI5FdaTUuXVsIuJBmkFJKb1eSzalzWVPJq0/wQ0z+Kp+vO968yjLjk1A3R1Bq6zo4yOlkkZgtRGlk21keSWFiVN+oFEmJnNcC9oLVygoSfDu9ejlBKYVpT9JIzVZS0oMOXJcdGOQTHDfJoriW9zgzKZBYTPt6ZbtbWD1xD9isiDDLAfKnHFJeefrqkN34Lc+YU/7Rpg2CLYtqvbpmu4JYtr4TiNrxZmh79eFwBZOSdkXPqzfvuJiJlWD6Lzyz8eZYGXqFuz9qR98WmQU4cl2x0wmPS0Yr6rdFeGafCeiVOQ4sg=
  app:
    master: gomocha-v2
  on:
    repo: amituuush/gomocha-v2
